name: Deno Lint and Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_and_fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run Deno lint
        run: deno lint

      - name: Check formatting
        run: deno fmt --check
